### ISSUE TITLE
[Fix comic] Drop Lupo Alberto comic

### ISSUE THREAD

**Issue by bitbooster** [sailfishos-applications/daily-comics#61]
**Daily Comics VERSION** (Daily Comics → [Top pulley] About): ***`1.9.9.5-beta1`***

*\<Please do name only a single comic / cartoon in each "fix comic" suggestion!\>*

#### NECESSARY DATA
- Name of the comic<br />
  ***Lupo Alberto***
- Denote the URL of a source page which allows for extracting a URL of a single image of the most recent, published strip by a RegEx (see next bullet point).  This source page may be identical to the home-page of the comic.<br />
  ***http://lupoalberto.agenzia2d.it/***

Fetching this comic returns error, and the reason is the content is no longer present at the listed URL. So I think this comic can be dropped from the list. 

#### ADDITIONAL INFORMATION
*\<Please consider thoroughly which other pieces of information might be relevant.\>*

The `stripSource` entry in the `lupoalberto/info.json` plugin points to http://lupoalberto.agenzia2d.it/ but at that URL nowadays there is just an empty page of the web hosting service. 
I visually checked also at the `homepage` (http://lupoalberto.it/), and while there is description of the comic, author, etc., I didn't find any pointer to a free daily/weekly comic script, only a few sample pdf for older stories.

**Comment by Olf0** [comment]
@bitbooster, thank you very much for indicating this.  This is unfortunate, because the [Lupo Alberto](https://en.wikipedia.org/wiki/Lupo_Alberto) comics by [Guido Silvestri](https://en.wikipedia.org/wiki/Guido_Silvestri) ("Silver") seem to have been well drawn and quite funny, but I double-checked and "yes", [the website](https://www.lupoalberto.it/) appears to be static nowadays and [the blog](https://lupoalbertoblog.blogspot.com/) ended in 2017.

Hence I deleted Lupo Alberto by PR #41.
